// Cozy Dogs - mini games: Memory Match, Cookie Catch, Guess the Breed, Rock-Paper-Scissors (rewards validated by server)
'use strict';
const GAMES=[['memory','🃏','Memory Match','จับคู่ภาพน้องหมาให้ครบ ยิ่งพลาดน้อยยิ่งได้เหรียญเยอะ','Flip cards and match every pair. Fewer moves = more coins.'],['catch','🍪','Cookie Catch','พาน้องหมารับขนมที่ร่วงลงมาภายใน 20 วินาที','Catch falling treats in 20 seconds.'],['guess','❓','Guess the Breed','ทายสายพันธุ์จากหน้าตา 5 ข้อ','Guess the breed from its look. 5 rounds.'],['rps','✊','Rock Paper Scissors','เป่ายิ้งฉุบ 1 ต่อ 1 กับผู้เล่นจริง ถ้าไม่มีใครอยู่บอทจะมาเล่นด้วย · ชนะรับ 30 เหรียญ (บอทรับครึ่งเดียว)','1v1 Rock-Paper-Scissors against a real player — a bot joins if nobody is around. Win 30 coins (half vs bots).']];
DO.games=()=>{const th=S.set.lang=='th';modal('games','🎮 '+t('Games'),`<div class="muted" style="margin-bottom:10px">${th?'รางวัลเหรียญจากมินิเกมจำกัดวันละ 500 เหรียญ':'Mini game coin rewards are capped at 500 per day.'}</div>`+GAMES.map(g=>`<div class="gmcard" data-do="gstart" data-g="${g[0]}"><span class="e">${g[1]}</span><div><b style="font-size:16px">${t(g[2])}</b><div class="muted">${th?g[3]:g[4]}</div></div></div>`).join(''),'sm')};
let gcleanup=null;
function gwin(title,body,onClose){if(gcleanup){gcleanup();gcleanup=null}const ov=modal('game',title,'<div class="mgb">'+body+'</div>','sm',{lock:0});ov.addEventListener('close',()=>{if(gcleanup){gcleanup();gcleanup=null}if(onClose)onClose()},{once:true});return ov}
DO.gstart=d=>{({memory:gMemory,catch:gCatch,guess:gGuess,rps:gRps})[d.g]()};
const shuffle=a=>{for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
function gEnd(g,score,extra=''){S.mgState={g,score};send({t:'mg_end',g,score});S.mgBody=extra}
H.mg_ok=m=>{const th=S.set.lang=='th',box=$('#mgres');const html=`<div class="big" style="margin:8px 0">${m.reward>0?'🎉 +'+m.reward+' '+ic('coin','big'):'—'}</div>${m.capped?`<div class="muted">${th?'ครบโควต้าเหรียญวันนี้แล้ว':'Daily coin cap reached'}</div>`:''}<div class="row" style="margin-top:10px"><button class="btn mint" data-do="gstart" data-g="${m.g}">${t('Again')}</button><button class="btn ghost" data-do="games">${t('Games')}</button></div>`;
 if(box)box.innerHTML=html;sfx(m.reward>0?'win':'lose');if(m.reward>0)toast('🎮 +'+m.reward+' 💰')};
// ---- Memory Match
function gMemory(){const ids=shuffle(Object.keys(DOGS.BR)).slice(0,8),cards=shuffle([...ids,...ids]);let open=[],moves=0,matched=0,lock=false;
 const ov=gwin('🃏 '+t('Memory Match'),`<div class="row" style="gap:20px;font-weight:900"><span>${t('Moves')}: <b id="mmv">0</b></span><span><b id="mmt">0</b>/8</span></div><div class="mem" id="memg">${cards.map((id,i)=>`<button class="mc" data-i="${i}"><div class="in"><div class="b"></div><div class="f">${thumbHTML(id,'Normal',40,null)}</div></div></button>`).join('')}</div><div id="mgres" class="center"></div>`);paintThumbs(ov);send({t:'mg_start',g:'memory'});
 $('#memg',ov).onclick=e=>{const b=e.target.closest('.mc');if(!b||lock||b.classList.contains('fl'))return;sfx('flip');b.classList.add('fl');open.push(b);if(open.length==2){moves++;$('#mmv',ov).textContent=moves;const[a,c]=open;
  if(cards[+a.dataset.i]==cards[+c.dataset.i]){a.classList.add('ok');c.classList.add('ok');matched++;{const mt=$('#mmt',ov);if(mt)mt.textContent=matched}open=[];sfx('ok');if(matched==8){setTimeout(()=>{$('#memg',ov).insertAdjacentHTML('afterend',`<div class="big">🎉 ${moves} ${t('Moves')}</div>`);gEnd('memory',moves)},500)}}
  else{lock=true;setTimeout(()=>{a.classList.remove('fl');c.classList.remove('fl');open=[];lock=false},750)}}}}
// ---- Cookie Catch
function gCatch(){const ov=gwin('🍪 '+t('Cookie Catch'),`<div class="row" style="gap:20px;font-weight:900"><span>${t('Time')}: <b id="ctm">20</b></span><span>${t('Score')}: <b id="csc">0</b></span></div><canvas id="catchc" width="480" height="360"></canvas><div id="mgres" class="center"><div class="muted">${S.set.lang=='th'?'ลากเมาส์/นิ้ว หรือกดลูกศร ซ้าย-ขวา':'Drag, or use ← → keys'}</div><button class="btn pink" id="cgo" style="margin-top:6px">${t('Start')}</button></div>`);
 const c=$('#catchc',ov),g=c.getContext('2d');const dog=DOGS.thumb(S.avatarBreed||'corgi','Normal',40,{noShadow:1,noGlow:1});let run=false,px=240,items=[],score=0,tl=20,last=0,spawn=0,raf=0,keys={};
 const kd=e=>{keys[e.key]=true},ku=e=>{keys[e.key]=false};addEventListener('keydown',kd);addEventListener('keyup',ku);
 const mv=e=>{const r=c.getBoundingClientRect();px=clamp((e.clientX-r.left)/r.width*480,36,444)};c.addEventListener('pointermove',mv);c.addEventListener('pointerdown',mv);
 gcleanup=()=>{run=false;cancelAnimationFrame(raf);removeEventListener('keydown',kd);removeEventListener('keyup',ku)};
 const draw=()=>{g.clearRect(0,0,480,360);const gr=g.createLinearGradient(0,0,0,360);gr.addColorStop(0,'#9fdcff');gr.addColorStop(1,'#e6f6ff');g.fillStyle=gr;g.fillRect(0,0,480,360);g.fillStyle='#7ccb8a';g.fillRect(0,320,480,40);g.fillStyle='#5cbc6e';g.fillRect(0,320,480,5);g.font='28px sans-serif';g.textAlign='center';for(const it of items)g.fillText(it.e,it.x,it.y);g.imageSmoothingEnabled=false;g.drawImage(dog,px-48,232,96,96)};
 const step=ms=>{if(!run)return;const dt=Math.min(.05,(ms-last)/1000);last=ms;tl-=dt;spawn-=dt;if(keys.ArrowLeft||keys.a)px-=330*dt;if(keys.ArrowRight||keys.d)px+=330*dt;px=clamp(px,36,444);
  if(spawn<=0){spawn=.42-.12*(1-tl/20);const bad=Math.random()<.2;items.push({x:rnd(24,456),y:-20,v:rnd(110,190)+(20-tl)*6,e:bad?pick(['🥦','🧅']):pick(['🍪','🦴','🍖','🧁']),bad})}
  for(let i=items.length-1;i>=0;i--){const it=items[i];it.y+=it.v*dt;if(it.y>296&&it.y<340&&Math.abs(it.x-px)<42){score=Math.max(0,score+(it.bad?-1:1));items.splice(i,1);sfx(it.bad?'err':'coin');$('#csc',ov).textContent=score}else if(it.y>370)items.splice(i,1)}
  $('#ctm',ov).textContent=Math.max(0,Math.ceil(tl));draw();if(tl<=0){run=false;draw();$('#mgres',ov).innerHTML=`<div class="big">${t('Score')}: ${score}</div>`;gEnd('catch',score);return}raf=requestAnimationFrame(step)};
 draw();$('#cgo',ov).onclick=()=>{$('#mgres',ov).innerHTML='';run=true;last=performance.now();send({t:'mg_start',g:'catch'});raf=requestAnimationFrame(step)}}
// ---- Guess the Breed
function gGuess(){const ids=Object.keys(DOGS.BR),th=S.set.lang=='th';let round=0,score=0,correct=null;const ov=gwin('❓ '+t('Guess the Breed'),`<div id="gq"></div><div id="mgres" class="center"></div>`);send({t:'mg_start',g:'guess'});
 const next=()=>{if(round>=5){$('#gq',ov).innerHTML=`<div class="big center">${t('Score')}: ${score}/5</div>`;gEnd('guess',score);return}round++;correct=pick(ids);const wrong=shuffle(ids.filter(i=>i!=correct&&DOGS.BR[i].name!=DOGS.BR[correct].name)).slice(0,3),opts=shuffle([correct,...wrong]);
  $('#gq',ov).innerHTML=`<div class="muted center">${round}/5 · ${t('Score')} ${score}</div><div class="panel" style="width:200px;margin:8px auto;background:linear-gradient(#ffe9d0,#ffd6e4);padding:4px">${thumbHTML(correct,Math.random()<.7?'Normal':'Snow',100,null)}</div><div class="opts4">${opts.map(o=>`<button class="btn ghost" data-g="${o}">${esc(DOGS.BR[o].name)}</button>`).join('')}</div>`;paintThumbs($('#gq',ov));
  $$('.opts4 .btn',ov).forEach(b=>b.onclick=()=>{const ok=b.dataset.g==correct;if(ok)score++;sfx(ok?'ok':'err');$$('.opts4 .btn',ov).forEach(x=>{x.style.pointerEvents='none';if(x.dataset.g==correct)x.classList.replace('ghost','mint');else if(x==b&&!ok)x.classList.replace('ghost','red')});setTimeout(next,850)})};next()}
// ---- Rock Paper Scissors (matchmaking via server)
const RPS_E={R:'✊',P:'✋',S:'✌️'};
function gRps(){S.rpsActive=false;gwin('✊ '+t('Rock Paper Scissors'),`<div id="rpsb" class="center"><div class="muted">${S.set.lang=='th'?'ค้นหาคู่ต่อสู้ออนไลน์… ถ้าไม่มีใคร บอทจะมาเล่นด้วย':'Looking for an opponent… a bot joins if nobody shows up'}</div><div style="font-size:50px;margin:10px" class="rotsm">🔎</div><button class="btn ghost" data-do="rpscancel">${t('Cancel')}</button></div>`,()=>send({t:'rps_cancel'}));S.rps=true;send({t:'rps_find'})}
DO.rpscancel=()=>{send({t:'rps_cancel'});closeMod('game')};
H.rps_wait=()=>{};
H.rps_start=m=>{S.rpsPick=null;S.rpsActive=true;if(!modOpen('game'))gRps();const b=$('#rpsb');if(!b)return;sfx('notify');b.innerHTML=`<div class="big">${esc(S.name)} <span class="muted">Lv${m.my}</span> ⚔️ ${esc(m.vs)} <span class="muted">Lv${m.lvl}</span></div><div class="muted" style="margin:6px">${t('Time')}: <b id="rpst">25</b></div><div class="rps">${['R','P','S'].map(k=>`<button data-k="${k}">${RPS_E[k]}</button>`).join('')}</div><div id="rpsr" class="muted" style="margin-top:10px"></div>`;
 let n=25;const iv=setInterval(()=>{n--;const e=$('#rpst');if(e)e.textContent=n;if(n<=0||!$('#rpsb'))clearInterval(iv)},1000);$$('.rps button',b).forEach(x=>x.onclick=()=>{if(S.rpsPick)return;S.rpsPick=x.dataset.k;x.classList.add('on');sfx('flip');send({t:'rps_pick',v:x.dataset.k});$('#rpsr').textContent=S.set.lang=='th'?'รอคู่ต่อสู้…':'Waiting…'})};
H.rps_result=m=>{const b=$('#rpsb');S.rps=false;if(!S.rpsActive)return;S.rpsActive=false;sfx(m.r>0?'win':m.r<0?'lose':'pop');if(!b)return;      // a result of a match that was closed earlier must not paint over a new search
 const th=S.set.lang=='th';b.innerHTML=`<div style="display:flex;justify-content:center;gap:24px;align-items:center;font-size:64px"><div>${RPS_E[m.my]||'❔'}</div><div style="font-size:26px">VS</div><div>${RPS_E[m.op]||'❔'}</div></div><div class="big" style="margin:10px">${m.r>0?'🎉 '+(th?'ชนะ!':'You win!'):m.r<0?'😢 '+(th?'แพ้':'You lose'):'🤝 '+(th?'เสมอ':'Draw')}</div><div class="muted">+${m.gain} ${ic('coin','sm')}</div>${m.loss>0?`<div class="lossbox">−${m.loss} ${ic('coin','big')} <small>${th?'ค่าแพ้':'losing fee'}</small></div>`:''}<div class="row" style="margin-top:10px"><button class="btn mint" data-do="gstart" data-g="rps">${t('Again')}</button><button class="btn ghost" data-do="games">${t('Games')}</button></div>`};
