// Cozy Dogs - modals: shop, dogs, dog profile, capsule, collection, quests, friends, ranks, profile, settings, daily, help
'use strict';
function ask(text,yes,opts={}){const ov=modal('ask',opts.title||'❓','<p style="font-weight:800;font-size:15px;margin:4px 0 14px;white-space:pre-line">'+text+'</p><div class="row"><button class="btn ghost" data-do="closemod" data-id="ask">'+t('Cancel')+'</button><button class="btn '+(opts.cls||'pink')+'" id="askYes">'+(opts.yes||t('Confirm'))+'</button></div>','sm');$('#askYes',ov).onclick=()=>{closeMod('ask');yes()}}
// ================= SHOP =================
const STABS=[['food','Food','🍖'],['toy','Toys','🎾'],['furn','Furniture','🛋️'],['rug','Rugs','🟦'],['wall','Wall','🖼️'],['acc','Accessories','🎀'],['style','Styles','🎨'],['season','Season','🎃']];
DO.shop=()=>{if(S.edit&&false)return;S.shopTab=S.shopTab||'furn';renderShop()};
DO.stab=d=>{S.shopTab=d.k;renderShop()};
function renderShop(){const tab=S.shopTab,C=S.cat,inv=S.me.inv,season=C.season;let body='';
 const tabs=`<div class="tabs2">${STABS.map(([k,l,e])=>`<button class="${tab==k?'on':''}" data-do="stab" data-k="${k}">${e} ${t(l)}</button>`).join('')}</div>`;
 const card=(o)=>`<div class="gc ${o.off?'off':''}">${o.tag?`<span class="tag">${o.tag}</span>`:''}${o.vis}<div class="nm">${esc(o.n)}</div><div class="pr">${ic('coin','sm')} ${o.p}</div>${o.own?`<div class="muted" style="font-size:11px">${t('Owned')}: ${o.own}</div>`:''}<div class="row" style="width:100%"><button class="btn sm ${S.me.coins>=o.p&&!o.off?'mint':'dis'}" data-do="buy" data-id="${o.id}" data-n="1">${t('Buy')}</button>${o.x5?`<button class="btn sm ${S.me.coins>=o.p*5&&!o.off?'sky':'dis'}" data-do="buy" data-id="${o.id}" data-n="5">x5</button>`:''}</div></div>`;
 if(tab=='food')body=Object.entries(C.food).map(([id,f])=>card({id,n:f.n+' · +'+f.h+'🍖',p:f.p,vis:`<div style="font-size:50px;height:84px;line-height:84px">${f.e}</div>`,own:inv[id]||0,x5:1})).join('');
 else if(tab=='acc')body=Object.entries(C.acc).map(([id,a])=>{const off=a.season&&a.season!=season;return card({id,n:a.n,p:a.p,vis:`<div style="font-size:50px;height:84px;line-height:84px">${a.e}</div>`,own:inv[id]||0,off:off||(inv[id]||0)>=1,tag:a.season?nice(a.season):''})}).join('');
 else if(tab=='style')body=['wall','floor','light'].map(k=>{const T={wall:C.walls,floor:C.floors,light:C.lights}[k],lab={wall:'Wallpaper',floor:'Floor',light:'Lighting'}[k];
   return`<h4 style="margin:6px 0">${t(lab)}</h4><div class="grid">${Object.entries(T).map(([id,p])=>{const own=p==0||S.me.unlock[k].includes(id),cur=S.deco[k]==id&&S.owner==S.name;return`<div class="gc ${cur?'sel':''}"><canvas class="swatch" data-sw="${k}|${id}" width="136" height="90"></canvas><div class="nm" style="min-height:0">${nice(id)}</div>${own?`<button class="btn sm ${cur?'dis':'mint'}" data-do="deco" data-k="${k}" data-v="${id}">${cur?'✔':t('Open')=='Open'?'Use':'ใช้'}</button>`:`<button class="btn sm ${S.me.coins>=p?'pink':'dis'}" data-do="deco" data-k="${k}" data-v="${id}" data-p="${p}">${ic('lock','sm')} ${p}</button>`}</div>`}).join('')}</div>`}).join('');
 else{const cats=tab=='season'?['season']:[tab];body=Object.values(C.items).filter(d=>cats.includes(d.cat)).map(d=>{const off=d.season&&d.season!=season;return card({id:d.id,n:d.n,p:d.p,vis:itThumb(d.draw,d.pal,42),own:inv[d.id]||0,off,tag:d.season?(off?'🔒 '+nice(d.season):nice(d.season)):''})}).join('');
  if(tab=='season'&&!season)body=`<div class="muted" style="padding:10px">🎃 Oct · 🎄 Dec</div>`+body}
 const ov=modal('shop',`🛍️ ${t('Shop')} <span class="rw" style="font-size:14px;margin-left:10px">${ic('coin','sm')} ${S.me.coins}</span>`,tabs+(tab=='style'?body:`<div class="grid">${body}</div>`),'lg');
 paintItemThumbs(ov);$$('canvas[data-sw]',ov).forEach(c=>{const[k,id]=c.dataset.sw.split('|');c.getContext('2d').drawImage(ROOM.swatch(k,id,136,90),0,0)})}
DO.buy=d=>{send({t:'shop_buy',id:d.id,n:+d.n||1})};
DO.deco=d=>{if(S.owner!=S.name)return toast(S.set.lang=='th'?'ตกแต่งได้เฉพาะบ้านตัวเอง':'You can only decorate your own house');if(d.p&&+d.p>0)ask((S.set.lang=='th'?'ปลดล็อก ':'Unlock ')+nice(d.v)+' '+d.p+' 🪙 ?',()=>send({t:'deco',k:d.k,v:d.v}),{yes:t('Buy')});else send({t:'deco',k:d.k,v:d.v})};
// ================= DOGS =================
DO.dogs=()=>{send({t:'dogs_get'});S.dogF=S.dogF||'all';renderDogs()};
DO.dogf=d=>{S.dogF=d.k;renderDogs()};
function renderDogs(){const all=S.allDogs||[],f=S.dogF||'all';const BR=DOGS.BR;let list=all.filter(d=>f=='all'||(f=='home'&&!d.away)||(f=='away'&&d.away)||(f=='fav'&&d.fav));
 list.sort((a,b)=>(b.fav-a.fav)||RORD[BR[a.breed].r]-RORD[BR[b.breed].r]||BR[a.breed].name.localeCompare(BR[b.breed].name));
 const rel=S.relMode,sel=S.relSel||new Set(),RV={C:20,R:60,E:150,L:400,M:1000};const gain=[...sel].reduce((s,id)=>{const d=all.find(x=>x.id==id);return s+(d?RV[BR[d.breed].r]:0)},0);
 const home=all.filter(d=>!d.away).length,max=S.me.maxDogs||(S.welcome?S.welcome.max.house:8);
 const tabs=`<div class="tabs2">${[['all','All'],['home','At home'],['away','Away'],['fav','Favorites']].map(([k,l])=>`<button class="${f==k?'on':''}" data-do="dogf" data-k="${k}">${t(l)}</button>`).join('')}<span class="sp" style="flex:1"></span><span class="pill">🏠 ${home}/${max}</span><button class="btn sm ${rel?'red':'ghost'}" data-do="relmode">${rel?'✕':'🗑️'} ${t('Release')}</button></div>`;
 const grid=list.map(d=>{const b=BR[d.breed],on=sel.has(d.id);return`<div class="gc r-${b.r} ${on?'sel':''} ${d.away&&!rel?'off':''}" data-do="${rel?'relpick':'dogprof'}" data-id="${d.id}"><button class="fv ${d.fav?'on':''}" data-do="dogfav" data-id="${d.id}">⭐</button>${thumbHTML(d.breed,d.variant,42,d.acc)}<div class="nm">${esc(d.name)}</div>${rarTag(b.r)}<div class="muted" style="font-size:11px">${PERS_EM[d.pers]||''} ${nice(d.pers)}</div>${rel?'':`<button class="btn sm ${d.away?'ghost':'mint'}" data-do="doghome" data-id="${d.id}" data-on="${d.away?1:0}">${d.away?'🏠 +':'🏠 ✔'}</button>`}</div>`}).join('');
 const ov=modal('dogs',`🐶 ${t('Dogs')} (${all.length})`,tabs+`<div class="grid">${grid||'<div class="muted">—</div>'}</div>`+(rel?`<div class="row" style="margin-top:12px;position:sticky;bottom:0"><div class="panel" style="padding:8px 12px;flex:2;font-weight:900">${t('Selected')}: ${sel.size} · +${gain} ${ic('coin','sm')}</div><button class="btn red ${sel.size?'':'dis'}" data-do="relgo">${t('Release')}</button></div>`:''),'lg');paintThumbs(ov)}
DO.relmode=()=>{S.relMode=!S.relMode;S.relSel=new Set();renderDogs()};
DO.relpick=(d,el,e)=>{if(e.target.closest('.fv'))return;const s=S.relSel||(S.relSel=new Set()),dg=(S.allDogs||[]).find(x=>x.id==d.id);if(dg&&dg.fav)return toast('⭐ '+(S.set.lang=='th'?'ปล่อยตัวโปรดไม่ได้':'Favorites cannot be released'));s.has(d.id)?s.delete(d.id):s.add(d.id);renderDogs()};
DO.relgo=()=>{const ids=[...S.relSel||[]];if(!ids.length)return;ask((S.set.lang=='th'?`ปล่อยน้องหมา ${ids.length} ตัว?\nจะไม่สามารถนำกลับมาได้`:`Release ${ids.length} dog(s)? This cannot be undone.`),()=>{send({t:'release',ids});S.relMode=false;S.relSel=new Set()},{cls:'red',yes:t('Release')})};
DO.dogfav=(d,el,e)=>{e.stopPropagation();send({t:'dog_fav',dog:d.id})};
DO.doghome=(d,el,e)=>{e.stopPropagation();send({t:'dog_home',dog:d.id,on:d.on=='1'})};
// ---- dog profile
DO.dogprof=d=>openProfile(d.id);
const POSES=[['stand','😊'],['walk','🚶'],['run','🏃'],['sit','🪑'],['sleep','💤'],['bark','🗨️'],['play','🎾'],['eat','🍖'],['happy','😆'],['sniff','👃'],['stretch','🥱'],['shy','🙈']];
function openProfile(id){const d=(S.allDogs||[]).find(x=>x.id==id)||S.dogs[id];if(!d)return;S.profId=id;S.profPose=S.profPose||'stand';renderProfile()}
function renderProfile(){const d=(S.allDogs||[]).find(x=>x.id==S.profId)||S.dogs[S.profId];if(!d)return;const b=DOGS.BR[d.breed],inv=S.me.inv,own=S.owner==S.name||true;const age=Math.max(0,Math.floor((Date.now()-d.born)/864e5));
 const TR=S.cat.tricks,TE={sit:'🐶',shake:'🤝',spin:'🌀',jump:'⬆️',roll:'🔄',dead:'💀'};
 const accs=Object.entries(S.cat.acc).filter(([k])=>(inv[k]||0)>0);
 const bar=(l,v,c)=>`<div class="bar"><b style="width:56px">${t(l)}</b><i><u style="width:${v}%;background:${c}"></u></i></div>`;
 const html=`<div class="row" style="align-items:flex-start;flex-wrap:wrap;gap:14px"><div style="flex:none;width:min(300px,100%)"><div class="panel" style="background:linear-gradient(#ffe9d0,#ffd6e4);padding:6px;position:relative"><canvas id="profc" width="300" height="230" style="width:100%;display:block;border-radius:8px;cursor:pointer" data-do="profpose"></canvas><div style="position:absolute;right:8px;top:6px">${rarTag(b.r)}</div></div>
 <div class="sel-row" style="margin-top:6px">${POSES.map(([k,e])=>`<button class="opt ${S.profPose==k?'on':''}" style="padding:2px 7px" data-do="profposeset" data-k="${k}">${e}</button>`).join('')}</div></div>
 <div style="flex:1;min-width:230px"><div class="row"><input id="pname" value="${esc(d.name)}" maxlength="12" style="flex:1;border:3px solid var(--ink);border-radius:10px;padding:6px 10px;font-weight:900;font-size:16px;user-select:text"><button class="btn sm sky" data-do="rename" data-id="${d.id}">${t('Rename')}</button></div>
 <div class="kv" style="margin:10px 0"><b>${t('Breeds')}</b><span>${esc(b.name)}${d.variant!='Normal'?' ('+t(d.variant)+')':''}</span><b>${t('Personality')}</b><span>${PERS_EM[d.pers]||''} ${nice(d.pers)}</span><b>${t('Favorite food')}</b><span>${(S.cat.food[String(d.favFood).toLowerCase()]||{}).e||''} ${esc(t(d.favFood))}</span><b>${t('Favorite toy')}</b><span>${esc(t(d.favToy))}</span><b>${t('Age')}</b><span>${age} ${S.set.lang=='th'?'วัน':'d'}</span></div>
 ${bar('Hunger',d.hunger,'#ffb36b')}${bar('Energy',d.energy,'#6fb8ff')}${bar('Happy',d.happy,'#ff8fb0')}${bar('Clean',d.clean,'#6fd1a5')}
 <div class="hearts" style="margin:6px 0">${t('Bond')}: ${Array.from({length:10},(_,i)=>ic(i<Math.floor(d.bond/10)?'heart':'hearte','sm')).join('')} <b>${d.bond}</b></div></div></div>
 <h4 style="margin:12px 0 6px">🎓 ${t('Tricks')}</h4><div class="sel-row">${TR.map(([k,need])=>{const has=(d.tricks||[]).includes(k);return`<span class="opt ${has?'on':''}" style="${has?'':'opacity:.55'}">${TE[k]} ${nice(k)} ${has?'✔':'<small>♥'+need+'</small>'}</span>`}).join('')}</div>
 <h4 style="margin:12px 0 6px">🎀 ${t('Accessories')}</h4><div class="sel-row"><button class="opt ${!d.acc?'on':''}" data-do="equip" data-id="${d.id}" data-a="">✕</button>${accs.map(([k,a])=>`<button class="opt ${d.acc==k?'on':''}" data-do="equip" data-id="${d.id}" data-a="${k}">${a.e} ${a.n}${(inv[k]||0)>1?' ×'+inv[k]:''}</button>`).join('')||`<button class="opt" data-do="stab" data-k="acc">🛍️ ${t('Shop')}</button>`}</div>
 <div class="row" style="margin-top:14px;flex-wrap:wrap"><button class="btn ${d.fav?'sun':'ghost'}" data-do="dogfav" data-id="${d.id}">⭐ ${t('Favorites')}</button><button class="btn mint" data-do="doghome" data-id="${d.id}" data-on="${d.away?1:0}">🏠 ${d.away?'+':'✔'}</button><button class="btn red" data-do="relone" data-id="${d.id}">🗑️ ${t('Release')}</button></div>`;
 const ov=modal('prof',`${esc(d.name)}`,html,'');startProfAnim(ov,d)}
let profRAF=0;
function startProfAnim(ov,d){cancelAnimationFrame(profRAF);const c=$('#profc',ov);if(!c)return;const g=c.getContext('2d'),b=DOGS.BR[d.breed],t0=performance.now();
 const P={stand:{state:'IDLE'},walk:{state:'WALK',mv:1},run:{state:'RUN',mv:1,run:1},sit:{state:'SIT'},sleep:{state:'SLEEP'},bark:{state:'BARK'},play:{state:'PLAY'},eat:{state:'EAT'},happy:{state:'IDLE',pet:1},sniff:{state:'SNIFF'},stretch:{state:'STRETCH'},shy:{state:'CORNER'}};
 const loop=()=>{if(!document.body.contains(c))return;const t=(performance.now()-t0)/1000;g.clearRect(0,0,300,230);g.save();g.fillStyle='rgba(60,32,22,.2)';g.beginPath();g.ellipse(150,196,66,11,0,0,7);g.fill();g.translate(150,196);g.scale(2.0*b.size,2.0*b.size);g.translate(0,(S.profPose=='run'||S.profPose=='walk')?-Math.abs(Math.sin(t*10))*3:0);
  DOGS.sprite(g,b,d.variant,t,Object.assign({seed:3,acc:d.acc,happy:true},P[S.profPose]||P.stand));g.restore();profRAF=requestAnimationFrame(loop)};loop()}
DO.profposeset=d=>{S.profPose=d.k;renderProfile()};
DO.profpose=()=>{const i=POSES.findIndex(p=>p[0]==S.profPose);S.profPose=POSES[(i+1)%POSES.length][0];renderProfile()};
DO.rename=d=>{const v=$('#pname').value.trim();if(v)send({t:'rename',dog:d.id,name:v})};
DO.equip=d=>{send({t:'equip',dog:d.id,acc:d.a||null})};
DO.relone=d=>{const dg=(S.allDogs||[]).find(x=>x.id==d.id);if(dg&&dg.fav)return toast('⭐ '+(S.set.lang=='th'?'ปล่อยตัวโปรดไม่ได้':'Favorites cannot be released'));ask(S.set.lang=='th'?'ปล่อยน้องหมาตัวนี้?':'Release this dog?',()=>{send({t:'release',ids:[d.id]});closeMod('prof')},{cls:'red',yes:t('Release')})};
// ================= CAPSULE =================
let capAnim=0;
DO.capsule=()=>renderCapsule();
function renderCapsule(){const m=S.me,W=S.welcome||{rates:{C:60,R:25,E:10,L:4,M:1},cost:100,pity:40};
 const ov=modal('capsule','🎰 '+t('Capsule'),`<div class="cap"><canvas id="capc" width="120" height="145"></canvas>
 <div class="pity"><div class="muted center" style="margin-bottom:3px">${t('Pity')}: ${m.pity}/${W.pity} ✨ ${t('Legendary')}+</div><div class="prog"><i style="width:${m.pity/W.pity*100}%;background:linear-gradient(#ffe48a,#ffb52e)"></i></div></div>
 <div class="acts2"><button class="btn pink ${m.coins>=W.cost?'':'dis'}" data-do="gacha" data-n="1">${ic('coin','sm')} ${W.cost} ×1</button><button class="btn pink ${m.coins>=W.cost*10?'':'dis'}" data-do="gacha" data-n="10">${ic('coin','sm')} ${W.cost*10} ×10</button><button class="btn sky ${m.tickets>=1?'':'dis'}" data-do="gacha" data-n="1" data-tk="1">${ic('ticket','sm')} 1 ×1</button><button class="btn sky ${m.tickets>=10?'':'dis'}" data-do="gacha" data-n="10" data-tk="1">${ic('ticket','sm')} 10 ×10</button></div>
 <div class="row" style="flex-wrap:wrap;justify-content:center;gap:6px">${Object.entries(W.rates).map(([r,p])=>`<span class="rar" style="background:${RCOL[r]};padding:2px 9px;white-space:nowrap">${t(RN[r])} ${p}%</span>`).join('')}</div></div>`,'sm');
 cancelAnimationFrame(capAnim);const c=$('#capc',ov),g=c.getContext('2d'),d=ITEMART.D(g,0,0);g.imageSmoothingEnabled=false;
 const draw=()=>{if(!document.body.contains(c))return;const t=performance.now()/1000,shake=S.capShake?Math.sin(t*50)*2:0;g.clearRect(0,0,120,145);g.save();g.translate(Math.round(shake),0);
  d.bx(12,102,96,38,'#ff8fb0',2);d.r(14,108,92,2,'#ffc0d4');d.bx(42,112,36,22,'#fff3df',1);d.r(52,118,16,10,'#5a3d33');d.r(54,120,12,6,'#2a1a18');d.e(24,122,6,6,'#ffc94d');d.e(24,122,3,3,'#e8a020');d.bx(86,120,14,8,'#6fd1a5',1);
  g.fillStyle='rgba(190,230,255,.55)';d.e(60,56,48,48,'rgba(190,230,255,.55)');d.e(60,56,44,44,'rgba(220,244,255,.6)');
  const cols=['#ff6b8a','#ffc94d','#6fd1a5','#6fb8ff','#b79bff','#ff9a4d'];for(let i=0;i<16;i++){const a=i*2.4+Math.sin(t*(S.capShake?9:.7)+i)*.25,r=8+(i%5)*7,x=60+Math.cos(a)*r,y=62+Math.abs(Math.sin(a))*18-(i%3)*10;d.se(Math.round(x),Math.round(y),5,5,cols[i%6])}
  d.r(14,52,2,40,'rgba(255,255,255,.0)');g.fillStyle='rgba(255,255,255,.7)';g.fillRect(30,24,3,22);g.fillRect(34,20,8,3);d.bx(20,100,80,6,'#ffe9f0',0);g.restore();capAnim=requestAnimationFrame(draw)};draw()}
// One pull at a time. While a request is in flight the buttons are locked; if several answers ever arrive together (slow connection, two tabs, a frantic double tap)
// the result screens are shown one after another - never stacked on top of each other (stacked screens used to share one OK button id, so OK stopped working).
let capSeen=new Set(),capQ=[],capOpen=0,capLab=null;
function capUnlock(){S.capBusy=0;renderCapsuleIfOpen()}
DO.gacha=d=>{const n=+d.n,tk=!!d.tk;if(capOpen||capQ.length||(S.capBusy&&Date.now()-S.capBusy<6000))return;
 if(tk?S.me.tickets<n:S.me.coins<(S.welcome?S.welcome.cost:100)*n)return sfx('err'),toast(S.set.lang=='th'?'ไม่พอ':'Not enough');
 const stamp=S.capBusy=Date.now();setTimeout(()=>{if(S.capBusy===stamp)capUnlock()},6000);        // (no answer for 6 s: unlock the buttons again)
 $$('#mods [data-do=gacha]').forEach(b=>b.classList.add('dis'));S.capShake=true;sfx('shake');S.capPrev=[...S.me.owned];send({t:'capsule',n,ticket:tk});setTimeout(()=>S.capShake=false,1500)};
H.capsule=m=>{S.capBusy=0;S.capShake=false;
 if(!capOpen&&!capQ.length)capSeen=new Set(S.capPrev||S.me.owned);      // a fresh batch: "NEW!" means not owned before this pull
 capQ.push(m.res.map(r=>{const nw=!capSeen.has(r.breed);capSeen.add(r.breed);return Object.assign({nw},r)}));
 if(!capOpen)capNext();else if(capLab)capLab()};
function capNext(){const res=capQ.shift();if(!res){capOpen=0;return}capOpen=1;
 const best=res.reduce((a,r)=>RORD[r.r]<RORD[a]?r.r:a,'C'),one=res.length==1,th=S.set.lang=='th';
 const ov=document.createElement('div');ov.className='reveal';document.body.append(ov);if(document.activeElement&&document.activeElement.blur)document.activeElement.blur();
 let done=false;capLab=()=>{const b=$('.rclose',ov),n=capQ.length;if(b)b.textContent='OK'+(n?' · '+(th?'ยังมีอีก '+n:n+' more'):'')};   // ("OK · 2 more" while other results are waiting)
 const close=()=>{if(done)return;done=true;capLab=null;document.removeEventListener('keydown',key);ov.remove();if(capQ.length)return capNext();capOpen=0;renderCapsuleIfOpen();UI.cur()};
 const key=e=>{if((e.key=='Enter'||e.key==' '||e.key=='Escape')&&ov.querySelector('.rclose')){e.preventDefault();e.stopPropagation();close()}};document.addEventListener('keydown',key);
 const card=(r,big,extra='')=>{const b=DOGS.BR[r.breed];return`<div class="panel rcard r-${r.r}" style="border-color:${RCOL[r.r]};${big?'':'width:auto;'}${extra}">${r.r!='C'?'<div class="glow"></div>':''}<div style="position:relative">${r.nw?'<span class="tag" style="position:absolute;left:0;top:0;background:var(--pink);border:2px solid var(--ink);border-radius:8px;font-size:11px;font-weight:900;padding:0 6px;color:#fff">'+(th?'ใหม่!':'NEW!')+'</span>':''}${thumbHTML(r.breed,r.variant,big?85:42,null)}<h3>${esc(r.name)}</h3><div>${rarTag(r.r)}</div><div class="muted">${esc(b.name)}${r.variant!='Normal'?' · '+t(r.variant):''}${r.away?' · 🏠 '+(th?'บ้านเต็ม':'full'):''}</div></div></div>`};
 ov.innerHTML=one?`<div style="font-size:60px;animation:wob .3s infinite" id="egg">🥚</div>`:`<div style="font-size:60px;animation:wob .3s infinite">🥚🥚🥚</div>`;
 setTimeout(()=>{if(done)return;sfx('reveal',one?res[0].r:best);
  ov.innerHTML=(one?card(res[0],true):`<div class="rc10">${res.map((r,i)=>card(r,false,'animation-delay:'+i*.08+'s')).join('')}</div>`)+`<button class="btn pink rclose">OK</button>`;
  paintThumbs(ov);capLab();$('.rclose',ov).onclick=close;if(one&&res[0].r!='C')sparkle(400,300,0)},900)}
function renderCapsuleIfOpen(){if(modOpen('capsule'))renderCapsule()}
// ================= COLLECTION / QUESTS / ACH =================
DO.coll=()=>{send({t:'ach'});renderColl()};
function renderColl(){const BR=DOGS.BR,own=new Set(S.me.owned),list=Object.values(BR).sort((a,b)=>RORD[a.r]-RORD[b.r]||a.name.localeCompare(b.name)),n=own.size;
 const ms=(S.coll||[]).map(c=>`<div class="day ${c.claimed?'done':c.ok?'now':''}" style="min-width:74px"><b>${c.k}</b><span class="e">🎁</span><span class="rw" style="font-size:10px">${rewardTxt(c.r)}</span>${c.ok&&!c.claimed?`<button class="btn sm mint" data-do="collclaim" data-k="${c.k}" style="margin-top:3px">${t('Claim')}</button>`:c.claimed?'✔':'🔒'}</div>`).join('');
 const ov=modal('coll',`📖 ${t('Collection')} ${n}/${list.length}`,`<div class="prog" style="margin-bottom:10px"><i style="width:${n/list.length*100}%"></i></div><div style="display:flex;gap:6px;overflow-x:auto;padding:6px 2px 12px">${ms}</div>
 <div class="grid" style="grid-template-columns:repeat(auto-fill,minmax(104px,1fr))">${list.map(b=>{const o=own.has(b.id);return`<div class="gc r-${b.r} ${o?'':'off'}" style="padding:5px 4px">${thumbHTML(b.id,'Normal',34,null).replace('<canvas','<canvas '+(o?'':'data-dark="1" '))}<div class="nm" style="font-size:11px;min-height:26px">${o?esc(b.name):'???'}</div>${rarTag(b.r)}</div>`}).join('')}</div>`,'lg');paintThumbs(ov)}
DO.collclaim=d=>send({t:'coll_claim',k:+d.k});
DO.quests=()=>{send({t:'quests'});send({t:'ach'});S.qTab=S.qTab||'q';renderQuests()};
DO.qtab=d=>{S.qTab=d.k;renderQuests()};
function renderQuests(){const q=S.quests,a=S.ach||[];const tabs=`<div class="tabs2"><button class="${S.qTab=='q'?'on':''}" data-do="qtab" data-k="q">📜 ${t('Daily quests')}</button><button class="${S.qTab=='a'?'on':''}" data-do="qtab" data-k="a">🏆 ${t('Achievements')}</button></div>`;let body='';
 if(S.qTab=='q'){const L=q?q.list:[];body=L.map(x=>`<div class="li"><div class="g"><b>${esc(t(x.n))}</b><div class="prog"><i style="width:${x.prog/x.goal*100}%"></i></div><small>${x.prog}/${x.goal}</small></div><span class="rw">${rewardTxt(x.r)}</span><button class="btn sm ${x.claimed?'dis':x.prog>=x.goal?'mint':'dis'}" data-do="qclaim" data-i="${x.i}">${x.claimed?'✔':t('Claim')}</button></div>`).join('');
  if(q)body+=`<div class="li" style="background:#fff3c4"><div class="g"><b>🎉 ${t('Bonus')}</b><small>${S.set.lang=='th'?'ทำครบทุกภารกิจเพื่อรับโบนัส':'Complete all quests'}</small></div><span class="rw">100 ${ic('coin','sm')} 3 ${ic('gem','sm')} 1 ${ic('ticket','sm')}</span><button class="btn sm ${q.bonus.claimed?'dis':q.bonus.ready?'mint':'dis'}" data-do="qbonus">${q.bonus.claimed?'✔':t('Claim')}</button></div>`}
 else body=[...a].sort((x,y)=>((y.prog>=y.goal&&!y.claimed)-(x.prog>=x.goal&&!x.claimed))||(x.claimed-y.claimed)).map(x=>`<div class="li" style="${x.claimed?'opacity:.6':''}"><div class="g"><b>${esc(t(x.n))}</b><small>${esc(t(x.d))}</small><div class="prog"><i style="width:${x.prog/x.goal*100}%;background:linear-gradient(#ffe48a,#ffb52e)"></i></div><small>${fmt(x.prog)}/${fmt(x.goal)}</small></div><span class="rw">${rewardTxt(x.r)}</span><button class="btn sm ${x.claimed?'dis':x.prog>=x.goal?'mint':'dis'}" data-do="aclaim" data-id="${x.id}">${x.claimed?'✔':t('Claim')}</button></div>`).join('');
 modal('quests','📜 '+t('Quests'),tabs+`<div class="list">${body}</div>`)}
DO.qclaim=d=>send({t:'quest_claim',i:+d.i});DO.qbonus=()=>send({t:'quest_bonus'});DO.aclaim=d=>send({t:'ach_claim',id:d.id});
// ================= FRIENDS / RANKS =================
DO.friends=()=>{send({t:'friends'});S.fTab=S.fTab||'f';renderFriends()};
DO.ftab=d=>{S.fTab=d.k;renderFriends()};
function renderFriends(){const f=S.fr||{friends:[],inReq:[],outReq:[],gifted:{},today:''},tab=S.fTab||'f';
 const tabs=`<div class="tabs2"><button class="${tab=='f'?'on':''}" data-do="ftab" data-k="f">👥 ${t('Friends')} (${f.friends.length})</button><button class="${tab=='r'?'on':''}" data-do="ftab" data-k="r">📨 ${f.inReq.length?`<span style="color:#d13c4c">(${f.inReq.length})</span>`:''} ${S.set.lang=='th'?'คำขอ':'Requests'}</button><button class="${tab=='a'?'on':''}" data-do="ftab" data-k="a">➕ ${t('Add')}</button></div>`;
 const row=(p,btns)=>`<div class="li">${avCirc(p.av,p.dog,46)}<div class="g"><b>${esc(p.name)}</b><small>Lv${p.lvl} · ${p.online?'🟢 '+t('Online'):'⚪ '+t('Offline')}</small></div>${btns}</div>`;let body='';
 if(tab=='f')body=f.friends.length?f.friends.map(p=>row(p,`<button class="btn sm sky" data-do="visit" data-n="${esc(p.name)}">🏡 ${t('Visit')}</button><button class="btn sm ${p.online?'lav':'dis'}" data-do="tradereq" data-n="${esc(p.name)}" title="${t('Trade')}">🔁</button><button class="btn sm ${f.gifted[p.name]==f.today?'dis':'pink'}" data-do="fgift" data-n="${esc(p.name)}">🎁</button><button class="btn sm ghost" data-do="fdel" data-n="${esc(p.name)}">✕</button>`)).join(''):emptyState('ยังไม่มีเพื่อนเลย~ ลองเพิ่มจากแท็บ ➕ หรือแตะผู้เล่นในสวนดูนะ','No friends yet~ add some from the ➕ tab, or tap a player in the park','👥');
 else if(tab=='r')body=(f.inReq.map(p=>row(p,`<button class="btn sm mint" data-do="fok" data-n="${esc(p.name)}">${t('Accept')}</button><button class="btn sm ghost" data-do="fno" data-n="${esc(p.name)}">✕</button>`)).join('')||emptyState('ยังไม่มีคำขอเป็นเพื่อน','No friend requests right now','📨'))+(f.outReq.length?`<div class="muted" style="margin-top:8px">${S.set.lang=='th'?'ส่งคำขอแล้ว':'Sent'}: ${f.outReq.map(esc).join(', ')}</div>`:'');
 else body=`<form id="faddf" class="row"><input id="faddn" maxlength="16" placeholder="${t('Username')}" style="border:3px solid var(--ink);border-radius:10px;padding:8px 10px;font-weight:800;user-select:text"><button class="btn pink" style="flex:none">${t('Add')}</button></form>`+(S.players.filter(p=>p.name!=S.name&&!f.friends.some(x=>x.name==p.name)).map(p=>`<div class="li" style="margin-top:8px"><div class="g"><b>${esc(p.name)}</b><small>Lv${p.lvl} · 🟢</small></div><button class="btn sm pink" data-do="fadd" data-n="${esc(p.name)}">➕</button></div>`).join(''));
 const ov=modal('friends','👥 '+t('Friends'),tabs+`<div class="list">${body}</div>`,'sm');paintThumbs(ov);const fm=$('#faddf',ov);if(fm)fm.onsubmit=e=>{e.preventDefault();const v=$('#faddn').value.trim();if(v){send({t:'friend_add',name:v});$('#faddn').value=''}}}
DO.fadd=d=>send({t:'friend_add',name:d.n});DO.fok=d=>send({t:'friend_ok',name:d.n});DO.fno=d=>send({t:'friend_no',name:d.n});DO.fdel=d=>ask((S.set.lang=='th'?'ลบ ':'Remove ')+d.n+'?',()=>send({t:'friend_del',name:d.n}),{cls:'red'});DO.fgift=d=>send({t:'friend_gift',name:d.n});
DO.ranks=()=>{send({t:'lb'});S.lbTab=S.lbTab||'level';renderRanks()};
DO.lbtab=d=>{S.lbTab=d.k;renderRanks()};
function renderRanks(){const lb=S.lb,tab=S.lbTab||'level';const tabs=`<div class="tabs2">${[['level','⭐ '+t('Level')],['breeds','📖 '+t('Breeds')],['wins','⚔️ '+t('Wins')],['arcade','🎮 '+TT('Arcade','อาร์เคด')],['likes','❤️ '+TT('Likes','ถูกใจ')],['cozy','🛋️ '+TT('Cozy','อบอุ่น')],['wishes','💭 '+TT('Wishes','คำขอ')]].map(([k,l])=>`<button class="${tab==k?'on':''}" data-do="lbtab" data-k="${k}">${l}</button>`).join('')}</div>`;
 const L=(lb&&lb[tab])||[],me=lb&&lb.rank?lb.rank[tab]:0,med=['🥇','🥈','🥉'];
 modal('ranks','🏆 '+t('Leaderboard'),tabs+`<div class="list">${L.map((x,i)=>`<div class="li" style="${x.n==S.name?'background:#fff3c4':''}"><b style="width:34px;font-size:20px;text-align:center">${med[i]||i+1}</b>${avCirc(((lb&&lb.avs)||{})[x.n],null,40)}<div class="g"><b>${esc(x.n)}</b><small>Lv${x.lvl}</small></div><span class="rw">${tab=='level'?'XP '+fmt(x.v):x.v}</span></div>`).join('')||emptyState('ยังไม่มีอันดับในหมวดนี้ — เป็นคนแรกเลย!','No rankings here yet — be the first!','🏆')}</div><div class="center muted" style="margin-top:8px">${t('Rank')}: #${me||'-'}</div>`,'sm')}
// ================= PROFILE / SETTINGS / DAILY / HELP =================
DO.profile=()=>{const m=S.me,st=m.stats||{};modal('profile','👤 '+t('Profile'),`<div class="center">${m.av?`<div class="pstage panel"><canvas id="pstage" width="320" height="170"></canvas></div>`:`<div style="width:90px;height:90px;margin:0 auto;border:3px solid var(--ink);border-radius:50%;background:var(--pink2);overflow:hidden">${S.avatarBreed?thumbHTML(S.avatarBreed,'Normal',45,null):''}</div>`}<div class="big" style="margin-top:8px">${esc(S.name)}${S.guest?' <small class="muted">(Guest)</small>':''}</div><div class="muted">${t('Level')} ${m.lvl} · XP ${m.xp%100}/100</div><div class="prog" style="width:200px;margin:6px auto 0"><i style="width:${m.xp%100}%"></i></div>${m.av?`<button class="btn pink sm" data-do="wardrobe" style="margin-top:8px">👕 ${TT('Change outfit','เปลี่ยนชุด')}</button>`:''}</div>
 <div class="stats">${[['🐶',t('Dogs'),m.total],['📖',t('Breeds'),m.owned.length+'/50'],['⚔️',t('Wins'),m.wins],['🎰',t('Capsule'),st.caps||0],['🤚',t('Pet'),st.pet||0],['🍖',t('Feed'),st.feed||0],['🎾',t('Play'),st.play||0],['🎓',t('Train'),st.train||0]].map(([e,l,v])=>`<div class="stc"><span class="e">${e}</span><b>${v}</b><small>${l}</small></div>`).join('')}</div>${S.guest?`<div class="muted center">${S.set.lang=='th'?'Guest จะไม่ถูกบันทึกข้ามอุปกรณ์ — สมัครบัญชีเพื่อเล่นต่อ':'Guest progress is temporary — register to keep your dogs.'}</div>`:''}`,'sm');paintThumbs();const ps=$('#pstage');if(ps)AVA.stage(ps,()=>S.me.av?{av:S.me.av,pose:'walk',dog:Wardrobe.myDog()}:null)};
DO.settings=()=>renderSettings();
function renderSettings(){const s=S.set,tg=(k,l)=>`<div class="toggle"><span>${t(l)}</span><div class="sw ${s[k]?'on':''}" data-do="tog" data-k="${k}"></div></div>`,opts=(k,list)=>`<div class="sel-row">${list.map(([v,l])=>`<button class="opt ${s[k]==v?'on':''}" data-do="setopt" data-k="${k}" data-v="${v}">${t(l)}</button>`).join('')}</div>`;
 modal('settings','⚙️ '+t('Settings'),`${tg('sound','Sound')}${tg('music','Music')}<div class="toggle"><span>${t('Volume')}</span><input class="slider" type="range" min="0" max="1" step=".05" value="${s.vol}" id="volr" style="width:55%"></div>${tg('names','Names')}${tg('particles','✨ Effects')}
 <div style="margin:10px 0 4px;font-weight:900">${t('Language')}</div>${opts('lang',[['th','ไทย'],['en','English']])}<div style="margin:10px 0 4px;font-weight:900">${t('Weather')}</div>${opts('weather',[['auto','Auto'],['sunny','Sunny'],['cloudy','Cloudy'],['rain','Rain'],['snow','Snow']])}<div style="margin:10px 0 4px;font-weight:900">${t('Time of day')}</div>${opts('time',[['auto','Auto'],['morning','Morning'],['noon','Noon'],['evening','Evening'],['night','Night']])}
 <div class="row" style="margin-top:16px"><button class="btn ghost" data-do="help">❓ ${S.set.lang=='th'?'วิธีเล่น':'Help'}</button><button class="btn red" data-do="logout">${t('Log out')}</button></div>`,'sm');
 const v=$('#volr');if(v)v.oninput=()=>{S.set.vol=+v.value;saveSet();applyVol()}}
DO.tog=d=>{S.set[d.k]=!S.set[d.k];saveSet();applyVol();if(d.k=='music'){S.set.music?startMusic():stopMusic()}renderSettings()};
DO.setopt=d=>{S.set[d.k]=d.v;saveSet();if(d.k=='lang'){applyLang();UI.all()}renderSettings();UI.loc()};
DO.logout=()=>{send({t:'logout',token:S.token});S.token=null;LS.set('cd_token',null);S.loaded=false;wantConn=false;try{S.ws.close()}catch{}location.reload()};
DO.photo=()=>photo();
DO.help=()=>modal('help','❓ '+(S.set.lang=='th'?'วิธีเล่น':'How to play'),(S.set.lang=='th'?`<div class="list"><div class="li"><span style="font-size:28px">👆</span><div class="g"><b>แตะน้องหมา</b><small>เลือกน้องหมาเพื่อดูแล แตะซ้ำเพื่อลูบหัว</small></div></div><div class="li"><span style="font-size:28px">🍖</span><div class="g"><b>ดูแลทุกวัน</b><small>ให้อาหาร เล่น หวีขน อาบน้ำ เพื่อเพิ่ม Bond และปลดล็อกลูกเล่น</small></div></div><div class="li"><span style="font-size:28px">🛋️</span><div class="g"><b>ตกแต่งบ้าน</b><small>ซื้อเฟอร์นิเจอร์ที่ร้านค้า แล้วลากวางในโหมดตกแต่ง</small></div></div><div class="li"><span style="font-size:28px">🎰</span><div class="g"><b>กาชา</b><small>สุ่มรับหมาใหม่ครบ 50 สายพันธุ์ มี Pity การันตี Legendary</small></div></div><div class="li"><span style="font-size:28px">📜</span><div class="g"><b>ภารกิจ & เพื่อน</b><small>ทำเควสรายวัน เยี่ยมบ้านเพื่อน ส่งของขวัญ เล่นมินิเกมหาเหรียญ</small></div></div><div class="li"><span style="font-size:28px">🌳</span><div class="g"><b>สวนหมา · แลกของ · ชุมชน</b><small>พาน้องหมาไปเดินกับผู้เล่นอื่น เก็บขนม เตะบอล · กดที่หมาของเพื่อนเพื่อแลกของ · ช่วยกันทำเป้าหมายประจำสัปดาห์</small></div></div></div>`:`<div class="list"><div class="li"><span style="font-size:28px">👆</span><div class="g"><b>Tap a dog</b><small>Select it to care for it; tap again to pet.</small></div></div><div class="li"><span style="font-size:28px">🍖</span><div class="g"><b>Care daily</b><small>Feed, play, brush and bathe to grow Bond and unlock tricks.</small></div></div><div class="li"><span style="font-size:28px">🛋️</span><div class="g"><b>Decorate</b><small>Buy furniture in the shop, then drag it into your room.</small></div></div><div class="li"><span style="font-size:28px">🎰</span><div class="g"><b>Capsule</b><small>Collect all 50 breeds. Pity guarantees a Legendary.</small></div></div><div class="li"><span style="font-size:28px">📜</span><div class="g"><b>Quests & friends</b><small>Daily quests, visit friends, send gifts, play mini games.</small></div></div><div class="li"><span style="font-size:28px">🌳</span><div class="g"><b>Park · Trading · Community</b><small>Walk your dog with other players, grab treats, kick the ball · tap a friend's dog to trade · work on the weekly goal together.</small></div></div></div>`),'sm');
DO.daily=()=>{const D=[{c:50},{c:80},{c:100},{c:150},{tk:1},{c:200},{g:10,c:300}],day=S.me.canClaim?((S.me.streak||0)%7)+1:S.me.streak||1;
 modal('daily','🎁 '+t('Daily Reward'),`<div class="days">${D.map((r,i)=>`<div class="day ${i+1==day&&S.me.canClaim?'now':i+1<day||(i+1==day&&!S.me.canClaim)?'done':''}"><b>${t('Day')} ${i+1}</b><span class="e">${r.g?'💎':r.tk?'🎟️':'🪙'}</span><span class="rw">${rewardTxt(r)}</span></div>`).join('')}</div><div class="center" style="margin-top:16px"><button class="btn pink ${S.me.canClaim?'':'dis'}" data-do="dclaim" style="font-size:18px;padding:10px 26px">${S.me.canClaim?t('Claim'):'✔ '+t('Claimed')}</button></div>`,'sm')};
DO.dclaim=()=>send({t:'daily'});
H.daily_ok=m=>{sfx('level');S.me.canClaim=false;toast('🎁 +'+[m.r.c&&m.r.c+'🪙',m.r.g&&m.r.g+'💎',m.r.tk&&m.r.tk+'🎟'].filter(Boolean).join(' '));if(modOpen('daily')){S.me.streak=m.day;DO.daily()}};
