// Cozy Dogs v5 - Thai strings for text that the server sends in English (quests, achievements, sets, perks, events, starter missions)
'use strict';
Object.assign(TH,{
'Dog Race':'แข่งวิ่งหมา','Treat Frenzy':'แย่งขนม','Odd Pup Out':'หาน้องหมาตัวแปลก','Bone Grab':'แย่งกระดูก','Breed Duel':'ดวลสายพันธุ์','House':'บ้าน','Mail':'จดหมาย','Games':'เกม','Grant a dog wish':'ทำตามคำขอของน้องหมา','Play an online mini-game':'เล่นมินิเกมออนไลน์','Dig 3 holes in the park':'ขุดหลุม 3 ครั้งในสวน','Play fetch with your dogs':'เล่นโยนบอลกับน้องหมา','Like a friend\'s house':'กดถูกใจบ้านเพื่อน','Spin the lucky wheel':'หมุนวงล้อนำโชค',
'Wish Granter':'ผู้ให้พร','Grant 10 dog wishes':'ทำตามคำขอ 10 ครั้ง','Dog Genie':'ยักษ์จินนี่สายหมา','Grant 50 dog wishes':'ทำตามคำขอ 50 ครั้ง','Treasure Hunter':'นักล่าสมบัติ','Dig 20 holes in the park':'ขุดหลุม 20 ครั้งในสวน','X Marks the Spot':'จุดกากบาทคือสมบัติ','Find the park treasure':'ขุดเจอสมบัติในสวน',
'Arcade Regular':'คอเกมอาร์เคด','Play 10 online games':'เล่นเกมออนไลน์ 10 ครั้ง','Arcade Champ':'แชมป์อาร์เคด','Win 5 online games':'ชนะเกมออนไลน์ 5 ครั้ง','Arcade Legend':'ตำนานอาร์เคด','Win 25 online games':'ชนะเกมออนไลน์ 25 ครั้ง',
'Party Animal':'สายปาร์ตี้','Host 3 parties':'จัดปาร์ตี้ 3 ครั้ง','Popular Pup':'ลูกหมายอดนิยม','Receive 10 house likes':'ได้รับถูกใจ 10 ครั้ง','Dream Home':'บ้านในฝัน','Upgrade your house to the max level':'อัปเกรดบ้านถึงระดับสูงสุด','Matching Set':'ชุดเข้าคู่','Complete 3 furniture sets':'จัดเฟอร์ครบ 3 ชุด',
'Feed a dog':'ให้อาหารน้องหมา','Pet your dogs 5 times':'ลูบหัวน้องหมา 5 ครั้ง','Buy something in the Shop':'ซื้อของในร้านค้า 1 ชิ้น','Place a furniture item':'วางเฟอร์นิเจอร์ 1 ชิ้น','Visit the dog park':'ไปสวนหมา',"Visit a friend's house":'ไปเยี่ยมบ้านเพื่อน','Play online games':'เล่นเกมออนไลน์','Grant dog wishes':'ทำตามคำขอน้องหมา','Dig up the park':'ขุดสมบัติในสวน',
'Pink Parlor':'ห้องรับแขกสีชมพู','Blue Lounge':'เลาจน์สีฟ้า','Indoor Garden':'สวนในบ้าน','Movie Night':'คืนดูหนัง','Reading Corner':'มุมอ่านหนังสือ','Play Room':'ห้องเล่น','Dog Cafe':'คาเฟ่น้องหมา',
'Dogs stay happier':'น้องหมามีความสุขนานขึ้น','Dogs tire more slowly':'น้องหมาเหนื่อยช้าลง','Dogs get hungry more slowly':'น้องหมาหิวช้าลง','+15% XP from care':'+15% XP จากการดูแล','+10% coins from wishes':'+10% เหรียญจากคำขอ','Petting gives +1 bond':'ลูบหัวได้ Bond +1','Wishes pay +25%':'คำขอให้รางวัล +25%',
'Halloween Party':'ปาร์ตี้ฮาโลวีน','Spooky season: +25% coins from wishes, park treats and spins':'เทศกาลสยองขวัญ: +25% เหรียญจากคำขอ ขนมในสวน และวงล้อ','Winter Festival':'เทศกาลฤดูหนาว','Festive season: +25% coins from wishes, park treats and spins':'เทศกาลแห่งความสุข: +25% เหรียญจากคำขอ ขนมในสวน และวงล้อ'});
